### ISSUE TITLE
Example for parsing multi-part polygons

### ISSUE THREAD

**Issue by grgcombs** [benasher44/shapeswift#1]
Playing around with this a little bit and I'm a bit stuck.  Trying to figure out how to code it such that it does the following:

1) iterates through a shapefile identifying all the features (only polygons in my case)
2) for each polygon, processes the each of the internal rings / parts and returns the coordinates

It also isn't clear how the projection is used, if ever.  In the ShapeSwiftTests.swift, SFSweepRoutesProjection is created but doesn't seem to be applied anywhere to invoke the Proj.4 framework.

I've gone as far as parsing custom shapefiles, like `TM_WORLD_BORDERS_SIMPL-0.3.shp`, and can successfully spit out the shape file header, but I'm stuck when it comes to iterating through the records in the shapefile.

**Comment by benasher44** [comment]
Woah! I'm excited to see that someone found this and is interested in playing with it! Unfortunately, this lib isn't ready to be consumed yet in any form. We've just begun implementing the different record types for the shapefile records, and we haven't started much on the other files that come with a shapefile yet. I'll update the README to reflect that this is a WIP.

Thanks for your interested though!
